import copy
import commands


class manipulation(commands.Command):
    """
    Class for all the manipulations commands
    Implements all the manipulation rules:
    ● If a colon : appears after the command's argument, then the original
    sequence is left untouched, and a new sequence is generated with the
    manipulation results.
    ● If an argument of the form @<new_seq_name> is provided after the colon, then
    this is the name of the new sequence.
    ● Otherwise, if @@ instead, then the name of the new sequence is automatically
    generated by the app.
    """

    def run_command(self, command):
        command = command.split(" ")
        try:
            dna = super().get_dna_holder().get_dna_by_id_or_name(command[1])
            if ":" in command:
                if not command[-1].startswith('@'):
                    raise Exception("in valid command")
                new_dna = copy.deepcopy(dna)
                if command[-1] != '@@':
                    new_dna.set_name(command[-1][1:])
                super().get_dna_holder().add_dna_object(new_dna)
                return super().get_dna_holder().get_dna_sequence()[-1], command[1:-2], command[-1][1:] if command[-1] != "@@" else None, True
            else:
                return dna, command[1:], False
        except Exception as error:
            if not error:
                raise Exception("in valid command")
            raise error



